server:
  port: 8090

security:
  jwt:
    public-key: classpath:public.txt
  oauth:
    access-token-uri: 'http://177.0.0.1:9092/oauth2/token'
    client-id: event-managment-service
    client-secret: rzv9pBSHclLoEaFmZ81PtmT03wAmaJSXLkOwi8tI=
    grant-type: password

database:
  host1: 'event-managment-db.cb6kiu4gsw4z.us-east-1.rds.amazonaws.com'
  host2: 'event-managment-db.cb6kiu4gsw5z.us-east-1.rds.amazonaws.com'
  host3: 'event-managment-db.cb6kiu4gsw6z.us-east-1.rds.amazonaws.com'
  port: 5432
  db-name: event_management_db

spring:
  datasource:
    master:
      url: jdbc:postgresql://${database.host1}:${database.port}/${database.db-name}?sslmode=require
      username: postgres
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 8
        connection-timeout: 30000
        idle-timeout: 600000
        connection-test-query: SELECT 1

    slave1:
      url: jdbc:postgresql://${database.host2}:${database.port}/${database.db-name}?sslmode=require
      username: postgres
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        connection-test-query: SELECT 1

    slave2:
      url: jdbc:postgresql://${database.host3}:${database.port}/${database.db-name}?sslmode=require
      username: postgres
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        connection-test-query: SELECT 1

  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 104.36.85.71
    port: 6969
    cache:
      cache-names: EVENTS
      redis:
        time-to-live: 300000

