server:
  port: 8090

security:
  jwt:
    public-key: classpath:public.txt
  oauth:
    access-token-uri: 'http://177.0.0.1:9092/oauth2/token'
    client-id: event-managment-service
    client-secret: rzv9pBSHclLoEaFmZ81PtmT03wAmaJSXLkOwi8tI=
    grant-type: password

database:
  host1: 'event-managment-db.cb6kiu4gsw4z.us-east-1.rds.amazonaws.com'
  host2: 'event-managment-db.cb6kiu4gsw5z.us-east-1.rds.amazonaws.com'
  host3: 'event-managment-db.cb6kiu4gsw6z.us-east-1.rds.amazonaws.com'
  port: 5432
  db-name: event_management_db

spring:
  datasource:
    master:
      url: jdbc:postgresql://${database.host1}:${database.port}/${database.db-name}?sslmode=require
      username: postgres
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 8
        connection-timeout: 30000
        idle-timeout: 600000
        connection-test-query: SELECT 1

    slave1:
      url: jdbc:postgresql://${database.host2}:${database.port}/${database.db-name}?sslmode=require
      username: postgres
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        connection-test-query: SELECT 1

    slave2:
      url: jdbc:postgresql://${database.host3}:${database.port}/${database.db-name}?sslmode=require
      username: postgres
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        connection-test-query: SELECT 1

  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
 redis:
   cluster:
    nodes:
      - 104.36.85.71:6969
      - 104.36.85.72:6969
      - 104.36.85.73:6969
    max-redirects: 5
   timeout: 5000 
   cache:
   cache-names: EVENTS
   redis:
     time-to-live: 300000
 cloud:
  openfeign:
   client:
    config:
     default:
      connectTimeout: 3000
      readTimeout: 5000

# Add replica for Master A
# redis-cli --cluster add-node 104.36.85.74:6369 104.36.85.71:6369 --cluster-slave --cluster-master-id <MasterA_ID>

# Add replica for Master B
# redis-cli --cluster add-node 104.36.85.75:6369 104.36.85.72:6369 --cluster-slave --cluster-master-id <MasterB_ID>

# Add replica for Master C
# redis-cli --cluster add-node 104.36.85.76:6369 104.36.85.73:6369 --cluster-slave --cluster-master-id <MasterC_ID>
