email:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}  # From environment variable
    password: ${EMAIL_PASSWORD}  # From environment variable
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  from:
    address: noreply@yourapp.com
    name: Your App Name
